{"name": "test_mul[10-5]", "status": "broken", "statusDetails": {"message": "NameError: name 'arg3' is not defined", "trace": "self = <test_Pages.test_app.Testcalculator object at 0x03D4BD60>, arg1 = 10, arg2 = 5\n\n    @pytest.mark.dependency(name='a')\n    @pytest.mark.parametrize('arg1,arg2',[(10,5)])\n    def test_mul(self,arg1,arg2):\n        print(arg1)\n>       print(arg3)\nE       NameError: name 'arg3' is not defined\n\ntest_app.py:20: NameError"}, "parameters": [{"name": "arg1", "value": "10"}, {"name": "arg2", "value": "5"}], "start": 1594281393973, "stop": 1594281393974, "uuid": "01e56951-1fe5-4ae4-8c22-990f568a2a79", "historyId": "d5b6d42d8a1b1bda24619b3c57d082b7", "testCaseId": "51937e377be594e534cf60b601bd43d8", "fullName": "test_app.Testcalculator#test_mul", "labels": [{"name": "tag", "value": "dependency(name='a')"}, {"name": "suite", "value": "test_app"}, {"name": "subSuite", "value": "Testcalculator"}, {"name": "host", "value": "DESKTOP-0J5JM67"}, {"name": "thread", "value": "7580-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_app"}]}